name: granvilleapp
description: Mobile version for the Granville Online Devlieries Website

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_rating_bar: ^3.0.1+1
  flutter_money_formatter: ^0.8.3
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica/HelveticaNeue_Light.ttf
          weight: 200
        - asset: fonts/helvetica/HelveticaNeue_Regular.ttf
          weight: 400
        - asset: fonts/helvetica/HelveticaNeue_Medium.ttf
          weight: 500
        - asset: fonts/helvetica/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: fonts/helvetica/HelveticaNeue_BlackCond.ttf
          weight: 900
